accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView,
    PasswordChangeDoneView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import reverse_lazy

from .views import RegistrationView

app_name = 'accounts'

urlpatterns = [
    # Login
    path(
        'login/',
        LoginView.as_view(template_name='accounts/login.html'),
        name='login'
    ),
    # Logout
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),

    # Change password
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='accounts/password_changed.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='accounts/password_change.html',
            success_url=reverse_lazy('accounts:password_change_done')
        ),
        name='password_change'
    ),

    # Reset password
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='accounts/password_reset/'
            'password_reset.html',
            subject_template_name='accounts/password_reset/'
            'email_subject.txt',
            email_template_name='accounts/password_reset/'
            'email_message.html',
            success_url=reverse_lazy('accounts:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='accounts/password_reset/'
            'email_sent.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password_reset_confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset/'
            'password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_reset_complete/',
        PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset/'
            'password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),

    # Registration
    path(
        'registration/',
        RegistrationView.as_view(),
        name='registration'
    )
]

api/urls.py
"""Urls for API"""

from django.urls import path, include
from rest_framework import routers

from api.views import (
    UserViewSet, BusStationViewSet, RouteViewSet,
    FlightViewSet, BusViewSet, DriverViewSet, TicketViewSet
)

# Slug will set after .../api/
SLUG_AND_VIEWSET = {
    'users': UserViewSet,
    'bus_stations': BusStationViewSet,
    'routes': RouteViewSet,
    'flights': FlightViewSet,
    'buses': BusViewSet,
    'drivers': DriverViewSet,
    'tickets': TicketViewSet,
}


api_router = routers.DefaultRouter()

for slug, view_set in SLUG_AND_VIEWSET.items():
    api_router.register(slug, view_set)


urlpatterns = [
    path(
        '', include(api_router.urls)
    )
]

avtovokzaltula_ru/urls.py
"""Urls for folder avtovokzaltula_ru"""

from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('bus_stations.urls')),
    path('accounts/', include('accounts.urls')),

    # For VK login
    path(
        'social/',
        include('social_django.urls', namespace='social')
    ),

    # Debug toolbar
    path(
        '__debug__/',
        include(debug_toolbar.urls)
    ),

    # Simple captcha
    path(
        'captcha/',
        include('captcha.urls')
    ),

    # API
    path(
        'api/',
        include('api.urls')
    ),

    # For login and logout in DRF
    path(
        'api-auth/',
        include('rest_framework.urls')
    )
]

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from captcha.fields import CaptchaField


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()
    captcha = CaptchaField()

    class Meta:
        fields = (
            'username', 'email',
            'password1', 'password2', 'captcha'
        )
        model = User

accounts/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from .forms import RegistrationForm


class RegistrationView(CreateView):
    form_class = RegistrationForm
    template_name = 'accounts/registration.html'
    success_url = reverse_lazy('accounts:login')

templates/accounts/login.html
{% extends 'layouts/default_form.html' %}
{% load static %}
{% block title %}Вход на сайт{% endblock title %}

{% block buttons %}
<input class='btn btn-primary' type="submit" value="Войти">
{% endblock buttons %}

{% block after_form %}
<p>
    <a class='text-dark' href="{% url 'accounts:password_reset' %}">
        Забыли пароль?
    </a>
</p>

<p>
    <a class='text-dark' href="{% url 'accounts:registration' %}">
        <input class='btn btn-success' type="submit" value="Регистрация">
    </a>
</p>

<p>
    <a href="{% url 'social:begin' 'vk-oauth2' %}">
        <img src="{% static 'accounts/img/vk.png' %}" alt="VK" height="50" width="50">
    </a>
</p>
{% endblock after_form %}

templates/accounts/password_change.html
{% extends 'layouts/default_form.html' %}

{% block title %}Смена пароля{% endblock title %}

{% block buttons %}
<input type="hidden" name="next" value='{{ next }}'>
<input class='btn btn-success' type="submit" value="Сохранить">
{% endblock buttons %}

templates/accounts/password_changed.html
{% extends 'layouts/implemented.html' %}

{% block title %}Пароль успешно изменён{% endblock title %}

{% block text %}
<h1>Пароль успешно изменён</h1>
{% endblock text %}

templates/accounts/registration.html
{% extends 'layouts/default_form.html' %}

{% block title %}Регистрация{% endblock title %}

{% block buttons %}
<input class='btn btn-success' type="submit" value="Зарегистрироваться">
{% endblock buttons %}