accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView,
    PasswordChangeDoneView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import reverse_lazy

from .views import RegistrationView

app_name = 'accounts'

urlpatterns = [
    # Login
    path(
        'login/',
        LoginView.as_view(template_name='accounts/login.html'),
        name='login'
    ),
    # Logout
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),

    # Change password
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='accounts/password_changed.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='accounts/password_change.html',
            success_url=reverse_lazy('accounts:password_change_done')
        ),
        name='password_change'
    ),

    # Reset password
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='accounts/password_reset/'
            'password_reset.html',
            subject_template_name='accounts/password_reset/'
            'email_subject.txt',
            email_template_name='accounts/password_reset/'
            'email_message.html',
            success_url=reverse_lazy('accounts:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='accounts/password_reset/'
            'email_sent.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password_reset_confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset/'
            'password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_reset_complete/',
        PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset/'
            'password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),

    # Registration
    path(
        'registration/',
        RegistrationView.as_view(),
        name='registration'
    )
]

api/urls.py
"""Urls for API"""

from django.urls import path, include
from rest_framework import routers

from api.views import (
    UserViewSet, BusStationViewSet, RouteViewSet,
    FlightViewSet, BusViewSet, DriverViewSet, TicketViewSet
)

# Slug will set after .../api/
SLUG_AND_VIEWSET = {
    'users': UserViewSet,
    'bus_stations': BusStationViewSet,
    'routes': RouteViewSet,
    'flights': FlightViewSet,
    'buses': BusViewSet,
    'drivers': DriverViewSet,
    'tickets': TicketViewSet,
}


api_router = routers.DefaultRouter()

for slug, view_set in SLUG_AND_VIEWSET.items():
    api_router.register(slug, view_set)


urlpatterns = [
    path(
        '', include(api_router.urls)
    )
]

avtovokzaltula_ru/urls.py
"""Urls for folder avtovokzaltula_ru"""

from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('bus_stations.urls')),
    path('accounts/', include('accounts.urls')),

    # For VK login
    path(
        'social/',
        include('social_django.urls', namespace='social')
    ),

    # Debug toolbar
    path(
        '__debug__/',
        include(debug_toolbar.urls)
    ),

    # Simple captcha
    path(
        'captcha/',
        include('captcha.urls')
    ),

    # API
    path(
        'api/',
        include('api.urls')
    ),

    # For login and logout in DRF
    path(
        'api-auth/',
        include('rest_framework.urls')
    )
]

bus_stations/urls.py
from django.urls import path

from .views import (
    Index, RoutesListView, FlightListView,
    SellTicketView, TicketListView,
    DeleteTicketView, ChequeForTicketView
)

app_name = 'bus_stations'

urlpatterns = [
    # Index
    path('', Index.as_view(), name='index'),

    # Bus station's routes
    path(
        '<bus_station_id>/routes/',
        RoutesListView.as_view(),
        name='routes'
    ),

    # Route's flights
    path(
        '<route_id>/flights/',
        FlightListView.as_view(),
        name='flights'
    ),

    # Sell ticket
    path(
        'sell_ticket/',
        SellTicketView.as_view(),
        name='sell_ticket'
    ),

    # Print all tickets
    path(
        'flight/<int:flight_id>/tickets/',
        TicketListView.as_view(),
        name='tickets',
    ),

    # Delete ticket
    path(
        'delete_ticket/<int:pk>/',
        DeleteTicketView.as_view(),
        name='delete_ticket'
    ),

    # Cheque for ticket
    path(
        'cheque_for_ticket/',
        ChequeForTicketView.as_view(),
        name='cheque_for_ticket'
    ),
]

templates/layouts/basic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Load Bootstrap -->
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css'
        integrity='sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2' crossorigin='anonymous'>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <link rel="stylesheet" href="{% static 'bus_stations/css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'bus_stations/img/favicon.ico' %}" />
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <style>
        .table_string_with_href:hover{
            background-color: #3DD042;
            cursor: pointer;
        }
    </style>

    <nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
        <a class='navbar-brand' href='{% url "bus_stations:index" %}'>
            <img src='{% static "bus_stations/img/logo.png" %}' width='50' height='50'>
            Главная
        </a>
        <div class='collapse navbar-collapse'>
            <div class='navbar-nav'>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class='dropdown-item' href='{% url "accounts:logout" %}'>
                            Выйти
                        </a>
                        <a class='dropdown-item' href='{% url "accounts:password_change" %}'>
                            Сменить пароль
                        </a>

                        {% if user.is_staff %}
                        <a class='dropdown-item' href='{% url "bus_stations:sell_ticket" %}'>
                            Продать билет
                        </a>
                        {% endif %}
                    </div>
                </li>
                <a class='nav-link' href='#'>
                </a>
                {% endif %}
            </div>
        </div>
    </nav>
    <section>
        {% block content %}
        {% endblock content %}
    </section>

    <script>
        $('.table_string_with_href').on('click', function(){
            let href = $(this).attr('href_for_click');
            document.location = href;
        })
    </script>
</body>

</html>

templates/layouts/default_form.html
{% extends 'layouts/basic.html' %}

{% block content %}
<div class="row">
    <div class="col-md-4 offset-4">
        <div class="text-center jumbotron">
            <form method="post">
                {% csrf_token %}

                <!-- Generic errors -->
                {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for error in form.non_field_errors %}
                        <li><em>{{ error }}</em></li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}

                {% for field in form.visible_fields %}
                <p>
                    {{ field.label_tag }}
                    <br>
                    {{ field }}
                </p>

                <!-- Field errors-->
                {% if field.errors %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    <em>{{ error }}</em>
                </div>
                {% endfor %}
                {% endif %}

                {% endfor %}

                <input type="hidden" name="next" value='{{ next }}'>
                {% block buttons %}
                {% endblock buttons %}
            </form>
            {% block after_form %}
            {% endblock after_form %}
        </div>
    </div>
</div>
{% endblock content %}

templates/layouts/implemented.html
{% extends 'layouts/basic.html' %}

{% block content %}
<div class="row">
    <div class="col-md-4 offset-4">
        <div class="text-center jumbotron">
            <p>
                {% block text %}
                {% endblock text %}
            </p>

            <p>
                <a href="{% url 'bus_stations:index' %}">
                    <input class='btn btn-success' type="submit" value="Главная">
                </a>
            </p>
        </div>
    </div>
</div>
{% endblock content %}