api/urls.py
"""Urls for API"""

from django.urls import path, include
from rest_framework import routers

from api.views import (
    UserViewSet, BusStationViewSet, RouteViewSet,
    FlightViewSet, BusViewSet, DriverViewSet, TicketViewSet
)

# Slug will set after .../api/
SLUG_AND_VIEWSET = {
    'users': UserViewSet,
    'bus_stations': BusStationViewSet,
    'routes': RouteViewSet,
    'flights': FlightViewSet,
    'buses': BusViewSet,
    'drivers': DriverViewSet,
    'tickets': TicketViewSet,
}


api_router = routers.DefaultRouter()

for slug, view_set in SLUG_AND_VIEWSET.items():
    api_router.register(slug, view_set)


urlpatterns = [
    path(
        '', include(api_router.urls)
    )
]

avtovokzaltula_ru/urls.py
"""Urls for folder avtovokzaltula_ru"""

from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('bus_stations.urls')),
    path('accounts/', include('accounts.urls')),

    # For VK login
    path(
        'social/',
        include('social_django.urls', namespace='social')
    ),

    # Debug toolbar
    path(
        '__debug__/',
        include(debug_toolbar.urls)
    ),

    # Simple captcha
    path(
        'captcha/',
        include('captcha.urls')
    ),

    # API
    path(
        'api/',
        include('api.urls')
    ),

    # For login and logout in DRF
    path(
        'api-auth/',
        include('rest_framework.urls')
    )
]

bus_stations/urls.py
from django.urls import path

from .views import (
    Index, RoutesListView, FlightListView,
    SellTicketView, TicketListView,
    DeleteTicketView, ChequeForTicketView
)

app_name = 'bus_stations'

urlpatterns = [
    # Index
    path('', Index.as_view(), name='index'),

    # Bus station's routes
    path(
        '<bus_station_id>/routes/',
        RoutesListView.as_view(),
        name='routes'
    ),

    # Route's flights
    path(
        '<route_id>/flights/',
        FlightListView.as_view(),
        name='flights'
    ),

    # Sell ticket
    path(
        'sell_ticket/',
        SellTicketView.as_view(),
        name='sell_ticket'
    ),

    # Print all tickets
    path(
        'flight/<int:flight_id>/tickets/',
        TicketListView.as_view(),
        name='tickets',
    ),

    # Delete ticket
    path(
        'delete_ticket/<int:pk>/',
        DeleteTicketView.as_view(),
        name='delete_ticket'
    ),

    # Cheque for ticket
    path(
        'cheque_for_ticket/',
        ChequeForTicketView.as_view(),
        name='cheque_for_ticket'
    ),
]

bus_stations/models.py
from django.db import models
from django.core.validators import MinValueValidator


class BusStation(models.Model):
    name = models.CharField(
        'Название',
        max_length=50,
        unique=True,
    )

    office_hours = models.CharField(
        'Часы работы',
        help_text='Часы работы через точку с запятой',
        max_length=30,
    )

    address = models.CharField(
        'Адрес',
        max_length=100,
        unique=True,
    )

    phone_number = models.CharField(
        'Номер телефона',
        max_length=15,
        unique=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Автовокзал'
        verbose_name_plural = 'Автовокзалы'
        ordering = ['name']


class Route(models.Model):
    name = models.CharField(
        'Название',
        help_text='Пункт прибытия',
        max_length=100,
    )

    regularity = models.CharField(
        'Регулярность',
        help_text='Первые 2 буквы дней недели через точку с запятой,\
            либо Еж - ежедневно',
        max_length=20,
    )

    departure_time = models.CharField(
        'Время отправления',
        help_text='Всё возможное время отправления',
        max_length=255,
    )

    price = models.PositiveSmallIntegerField(
        'Цена',
    )

    bus_station = models.ForeignKey(
        'BusStation',
        related_name='routes',
        on_delete=models.CASCADE,
        verbose_name='Автовокзал',
    )

    def __str__(self):
        return str(self.bus_station) + " - " + str(self.name)

    class Meta:
        verbose_name = 'Маршрут'
        verbose_name_plural = 'Маршруты'
        ordering = ['name']


class Flight(models.Model):
    route = models.ForeignKey(
        'Route',
        related_name='flights',
        on_delete=models.CASCADE,
        verbose_name='Маршрут'
    )

    departure_time = models.TimeField(
        'Время отправления',
    )

    arrival_time = models.TimeField(
        'Время прибытия',
    )

    amount_of_free_places = models.PositiveSmallIntegerField(
        'Число свободных мест',
        default=30,
    )

    bus = models.ForeignKey(
        'Bus',
        related_name='flights',
        on_delete=models.CASCADE,
        verbose_name='Автобус',
    )

    def __str__(self):
        return str(self.route) + " - " + \
            str(self.departure_time)

    class Meta:
        verbose_name = 'Рейс'
        verbose_name_plural = 'Рейсы'
        ordering = ['departure_time']
        unique_together = ['route', 'departure_time']


class Bus(models.Model):
    registration_number = models.CharField(
        'Регистрационный номер',
        max_length=10,
        primary_key=True,
    )

    mark = models.CharField(
        'Марка',
        max_length=100
    )

    amount_of_places = models.PositiveSmallIntegerField(
        'Число мест',
    )

    driver = models.OneToOneField(
        'Driver',
        on_delete=models.PROTECT,
        verbose_name='Водитель',
    )

    def __str__(self):
        return f'{self.mark} {self.registration_number}'

    class Meta:
        verbose_name = 'Автобус'
        verbose_name_plural = 'Автобусы'
        ordering = ['mark']


class Driver(models.Model):
    passport_number = models.CharField(
        'Номер паспорта',
        max_length=25,
        unique=True,
    )

    name = models.CharField(
        'Имя',
        max_length=255
    )

    second_name = models.CharField(
        'Фамилия',
        max_length=255
    )

    middle_name = models.CharField(
        'Отчество',
        max_length=255
    )

    phone_number = models.BigIntegerField(
        'Номер телефона',
        unique=True,
        validators=[MinValueValidator(1)]
    )

    age = models.PositiveSmallIntegerField(
        'Возраст',
        validators=[MinValueValidator(21)]
    )

    def __str__(self): return str(self.second_name) + " " + \
        str(self.name[0]) + "." + \
        str(self.middle_name[0]) + ". - " + \
        str(self.passport_number)

    class Meta:
        verbose_name = 'Водитель'
        verbose_name_plural = 'Водители'
        ordering = ['name', 'second_name', 'middle_name']


class Ticket(models.Model):
    flight = models.ForeignKey(
        'Flight',
        on_delete=models.PROTECT,
        verbose_name='Рейс',
    )

    user = models.CharField(
        'Покупатель',
        max_length=255
    )

    seller = models.CharField(
        'Продавец',
        max_length=255
    )

    registration_time = models.DateTimeField(
        'Время оформления',
        auto_now_add=True,
    )

    def __str__(self):
        return str(self.flight) + \
            " - " + \
            str(self.user)

    class Meta:
        verbose_name = 'Билет'
        verbose_name_plural = 'Билеты'
        ordering = ['flight']
        get_latest_by = 'registration_time'

bus_stations/forms.py
from django import forms

from .models import Ticket


class SellTicketForm(forms.ModelForm):
    class Meta:
        fields = '__all__'
        model = Ticket

bus_stations/views.py
from time import gmtime

from .models import (
    BusStation, Route, Flight,
    Bus, Driver, Ticket
)
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import (
    LoginRequiredMixin, UserPassesTestMixin
)
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView
from django.forms import ValidationError

from .forms import SellTicketForm


class Index(LoginRequiredMixin, ListView):
    template_name = 'bus_stations/index.html'
    context_object_name = 'bus_stations'
    queryset = BusStation.objects.all()


class RoutesListView(LoginRequiredMixin, ListView):
    template_name = 'bus_stations/bus_station_routes.html'
    context_object_name = 'routes'

    def get_queryset(self):
        return Route.objects.filter(
            bus_station=self.kwargs['bus_station_id']
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['bus_station'] = BusStation.objects.get(
            pk=self.kwargs['bus_station_id']
        )

        return context


class FlightListView(LoginRequiredMixin, ListView):
    template_name = 'bus_stations/route_flights.html'
    context_object_name = 'flights'

    def get_queryset(self):
        return Flight.objects.filter(
            route=self.kwargs['route_id']
        ).select_related('route', 'bus', 'route__bus_station')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['route'] = Route.objects.get(
            pk=self.kwargs['route_id']
        )

        # Next flight
        context['next_flight'] = get_next_flight(
            Flight.objects.filter(
                route=context['route']
            )
        )

        context['tickets'] = Ticket.objects.filter(
            flight__route=context['route']
        )

        context['travel_time'] = get_travel_time(
            Flight.objects.filter(
                route=self.kwargs['route_id']
            ).first().departure_time,
            Flight.objects.filter(
                route=self.kwargs['route_id']
            ).first().arrival_time
        )

        return context


class SellTicketView(UserPassesTestMixin, CreateView):
    form_class = SellTicketForm
    template_name = 'bus_stations/sell_ticket.html'
    success_url = reverse_lazy('bus_stations:cheque_for_ticket')

    def form_valid(self, SellTicketForm):
        sell_ticket_flight = Flight.objects.get(
            pk=self.get_form_kwargs()['data']['flight']
        )

        sell_ticket_flight.amount_of_free_places -= 1
        sell_ticket_flight.save()

        return super().form_valid(SellTicketForm)

    def test_func(self):
        return self.request.user.is_staff


class ChequeForTicketView(TemplateView):
    template_name = 'bus_stations/cheque_for_ticket.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['ticket'] = Ticket.objects.latest()

        return context


class TicketListView(UserPassesTestMixin, ListView):
    template_name = 'bus_stations/tickets.html'
    context_object_name = 'tickets'

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):
        return Ticket.objects.filter(
            flight=self.kwargs['flight_id'],
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['flight'] = Flight.objects.get(
            pk=self.kwargs['flight_id']
        )

        return context


class DeleteTicketView(UserPassesTestMixin, DeleteView):
    template_name = 'bus_stations/delete_ticket.html'
    model = Ticket
    success_url = reverse_lazy('bus_stations:index')

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        delete_ticket_flight = Flight.objects.get(
            pk=Ticket.objects.get(pk=self.kwargs['pk']).flight.pk
        )
        delete_ticket_flight.amount_of_free_places += 1
        delete_ticket_flight.save()

        return reverse_lazy(
            'bus_stations:tickets',
            args=[delete_ticket_flight.pk]
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context[
            'flight'
        ] = Flight.objects.get(
            pk=Ticket.objects.get(pk=self.kwargs['pk']).flight.pk
        )
        return context


def get_travel_time(departure_time, arrival_time):
    departure_hours_in_minute = int(str(departure_time)[:2]) * 60
    arrival_hours_in_minute = int(str(arrival_time)[:2]) * 60

    departure_minute = int(str(departure_time)[3:5])
    arrival_minute = int(str(arrival_time)[3:5])

    travel_minute = (arrival_hours_in_minute + arrival_minute) - \
        (departure_hours_in_minute + departure_minute)

    return f'{travel_minute // 60}:{travel_minute % 60}:00'


def get_next_flight(flights):
    current_hour = gmtime()[3] + 3
    current_minute = gmtime()[4]

    # Flights with departure hour more than current hour
    flights_after_current_hour = []
    for flight in flights:
        # If flight's departure hour more or equal than current hour
        if int(str(flight.departure_time)[:2]) >= current_hour:
            flights_after_current_hour.append(flight)
    if not flights_after_current_hour:
        return ''
    else:
        # Flights with departure time more than current time
        flights_after_current_time = []
        for flight in flights_after_current_hour:
            # If flight's departure minute more or equal than current minute
            if int(str(flight.departure_time)[3:5]) >= current_minute and \
                    int(str(flight.departure_time)[:2]) == current_hour:
                flights_after_current_time.append(flight)

            if int(str(flight.departure_time)[:2]) > current_hour:
                flights_after_current_time.append(flight)

        return get_flight_with_non_zero_free_places_amount(flights_after_current_time)


def get_flight_with_non_zero_free_places_amount(flights):
    for i in range(len(flights)):
        next_flight = flights[i]

        if next_flight.amount_of_free_places != 0:
            break
        else:
            while next_flight.amount_of_free_places == 0:
                i += 1
                if i >= len(flights):
                    next_flight = ''
                    break
                next_flight = flights[i]
                if next_flight.amount_of_free_places != 0:
                    break

    return next_flight

templates/bus_stations/all_tickets.html
{% extends 'layouts/basic.html' %}

{% block title %}
Список билетов
{% endblock title %}

{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-md-6 offset-3 text-center">
            <h4>
                <b>
                    Все билеты
                </b>
            </h4>
            <table width="100%">
                <tr>
                    <th width='100'>Автовокзал</th>
                    <th width='100'>Маршрут</th>
                    <th>Время отправления</th>
                    <th>Цена</th>
                    <th>Покупатель</th>
                    <th>Продавец</th>
                </tr>
                {% for ticket in tickets %}
                <tr>
                    <td>
                        <a class='text-dark' href="{% url 'bus_stations:routes' ticket.bus_station.pk %}">
                            {{ ticket.bus_station }}
                        </a>
                    </td>
                    <td>
                        <a class='text-dark' href="{% url 'bus_stations:flights' ticket.route.pk %}">
                            {{ ticket.route }}
                        </a>
                    </td>
                    <td>{{ ticket.departure_time }}</td>
                    <td>{{ ticket.price }} ₽</td>
                    <td>{{ ticket.user }}</td>
                    <td>{{ ticket.seller }}</td>
                    <td>
                        <a href="{% url 'bus_stations:delete_ticket' ticket.pk %}">
                            <input class='btn btn-danger' type="submit" value="Удалить">
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/bus_stations/bus_station_routes.html
{% extends 'layouts/basic.html' %}

{% block title %}
Список маршрутов автовокзала {{ bus_station }}
{% endblock title %}

{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-md-6 offset-3 text-center">
            <h4>
                <b>
                    Расписание отправлений с автовокзала {{ bus_station }}
                </b>
            </h4>
            <h6>
                <b>Адрес</b>: {{ bus_station.address }}
            </h6>
            <h6>
                <b>Телефон</b>: {{ bus_station.phone_number }}
            </h6>
            <table width="100%">
                <tr>
                    <th width='150'>Название маршрута</th>
                    <th width='120'>Регулярность</th>
                    <th width='300'>Время отправления</th>
                </tr>
                {% for route in routes %}
                <tr class="table_string_with_href" href_for_click="{% url 'bus_stations:flights' route.pk %}">
                    {# Name #}
                    <td>{{ route.name }}</td>

                    {# Regularity #}
                    <td>
                        {{ route.regularity }}
                    </td>

                    {# Departure time #}
                    <td>{{ route.departure_time }}</td>
                    {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/bus_stations/cheque_for_ticket.html
{% extends 'layouts/implemented.html' %}

{% block text %}
<h3>Чек для билета №{{ ticket.pk }}</h3>
<h5>Покупатель: {{ ticket.user }}</h5>
<h5>Рейс {{ ticket.flight }}</h5>
<h5>Кассир: {{ ticket.seller }}</h5>
<h5>Дата выдачи: {{ ticket.registration_time }}</h5>

<a href="{% url 'bus_stations:sell_ticket' %}">
    <input class='btn btn-primary' type="submit" value="Продать другой билет">
</a>
{% endblock text %}

templates/bus_stations/delete_ticket.html
{% extends 'layouts/basic.html' %}

{% block title %}Удаление билета{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-4 offset-4">
        <div class="jumbotron">
            <form class='text-center' method="post">
                {% csrf_token %}
                <h2>Вы точно хотите удалить этот билет?</h2>
                <p>
                    <input class='btn btn-danger' type="submit" value="Удалить">
                </p>
            </form>
            <p class='text-center'>
                <a href="{% url 'bus_stations:tickets' flight.pk %}">
                    <input class='btn btn-success' type="submit" value="Отмена">
                </a>
            </p>
        </div>
    </div>
</div>
{% endblock content %}

templates/bus_stations/index.html
{% extends 'layouts/basic.html' %}

{% block title %}Список автовокзалов{% endblock title %}

{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-md-6 offset-3">
            <h2 class='text-center'>Выберите автовокзал отправитель</h2>
            <table style="width:100%">
                <tr class='text-center'>
                    <th>Название автовокзала</th>
                    <th>Часы работы</th>
                    <th>Адрес</th>
                    <th>Телефон</th>
                </tr>
                {% for bus_station in bus_stations %}
                    <tr class="table_string_with_href" href_for_click="{% url 'bus_stations:routes' bus_station.pk %}">
                        {# Name #}
                        <td>{{ bus_station }}</td>

                        {# Office hours #}
                        <td class='text-center'>
                            {{ bus_station.office_hours }}
                        </td>

                        {# Address #}
                        <td>{{ bus_station.address }}</td>

                        {# Phone number #}
                        <td class='text-center'>
                            {{ bus_station.phone_number }}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/bus_stations/route_flights.html
{% extends 'layouts/basic.html' %}

{% block title %}
Рейсы маршрута {{ route.bus_station }} - {{ route }}
{% endblock title %}

{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-md-8 offset-2 text-center">
            <h4>
                <b>
                    Расписание отправлений с автовокзала <a class='text-dark'
                        href="{% url 'bus_stations:routes' route.bus_station.pk %}">{{ route.bus_station }}</a>
                </b>
            </h4>
            <h5>по маршруту {{ route }}</h5>
            <h5>на {% now 'd.m.Y' %}</h5>
            <table width="100%">
                <tr>
                    <th width='180'>Время отправления</th>
                    <th width='180'>Время прибытия</th>
                    <th width='180'>Время в пути</th>
                    <th width='150'>Маршрут</th>
                    <th width='220'>Число свободных мест</th>
                    <th width='180'>Цена билета</th>
                    <th width='130'>Автобус</th>
                    {% if user.is_staff %}
                    <th width='200'>Список проданных билетов</th>
                    {% endif %}
                </tr>

                {% for flight in flights %}
                <tr>
                    <!-- Departure time -->
                    <td>
                        {{ flight.departure_time }}
                    </td>

                    <!-- Arrival time -->
                    <td>
                        {{ flight.arrival_time }}
                    </td>

                    <!-- Travel time -->
                    <td>
                        {{ travel_time }}
                    </td>

                    <!-- Route -->
                    <td>
                        <a class='text-dark'
                            href="{% url 'bus_stations:routes' flight.route.bus_station.pk %}">{{ flight.route.bus_station }}</a>
                        - {{ route.name }}
                    </td>

                    <!-- Free places amount -->
                    <td>{{ flight.amount_of_free_places }}</td>

                    <!-- Ticket price -->
                    <td>{{ flight.route.price }} ₽</td>

                    <!-- Bus -->
                    <td>{{ flight.bus }}</td>

                    <!-- Sell tickets -->
                    {% if user.is_staff %}
                    <td>
                        <a class='dropdown-item' href='{% url "bus_stations:tickets" flight.pk %}'>
                            Проданные билеты
                        </a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </table>

            <!-- Next flight -->
            <br>
            {% if not next_flight.departure_time %}
            <h4>Ближайших рейсов нет</h4>
            {% else %}
            <h4 class='text-center'>Ближайший рейс</h4>
            <table width="100%">

                <!-- Departure time -->
                <td width='180'>
                    {{ next_flight.departure_time }}
                </td>

                <!-- Arrival time -->
                <td width='180'>
                    {{ next_flight.arrival_time }}
                </td>

                <!-- Travel time -->
                <td width='180'>
                    {{ travel_time }}
                </td>

                <!-- Route -->
                <td width='150'>
                    <a class='text-dark'
                        href="{% url 'bus_stations:routes' next_flight.route.bus_station.pk %}">{{ next_flight.route }}</a>
                </td>

                <!-- Free places amount -->
                <td width='220'>{{ next_flight.amount_of_free_places }}</td>

                <!-- Ticket price -->
                <td width='180'>{{ next_flight.route.price }} ₽</td>

                <!-- Bus -->
                <td width='130'>{{ next_flight.bus }}</td>

                <!-- Sell tickets -->
                {% if user.is_staff %}
                <td width='200'>
                    <a class='dropdown-item' href='{% url "bus_stations:tickets" next_flight.pk %}'>
                        Проданные билеты
                    </a>
                </td>
                {% endif %}
            </table>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/bus_stations/sell_ticket.html
{% extends 'layouts/default_form.html' %}
{% load static %}
{% block title %}Продажа билета{% endblock title %}

{% block buttons %}
<input class='btn btn-primary' type="submit" value="Продать">
{% endblock buttons %}

templates/bus_stations/tickets.html
{% extends 'layouts/basic.html' %}

{% block title %}
Список билетов
{% endblock title %}

{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-md-6 offset-3 text-center">
            {% if tickets %}
            <h3>
                <b>
                    Билеты на рейс {{ flight }}
                </b>
            </h3>
            <table width="100%">
                <tr>
                    <th width='100'>Рейс</th>
                    <th width='50'>Цена</th>
                    <th width='100'>Покупатель</th>
                    <th width='80'>Продавец</th>
                    <th width='100'>Удалить билет</th>
                </tr>
                {% for ticket in tickets %}
                <tr>
                    <td>{{ ticket.flight }}</td>
                    <td>{{ ticket.flight.route.price }} ₽</td>
                    <td>{{ ticket.user }}</td>
                    <td>{{ ticket.seller }}</td>
                    <td>
                        <a href="{% url 'bus_stations:delete_ticket' ticket.pk %}">
                            <input class='btn btn-danger' type="submit" value="Удалить">
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
            <h1>Билетов по данному рейсу нет</h1>
            {% endif %}
            <br>
            <a href="{% url 'bus_stations:flights' flight.route.pk %}">
                <input class='btn btn-success btn-lg' type="submit" value="Назад">
            </a>
        </div>
    </div>
</div>
{% endblock content %}